name = "bobzhang/atd_runtime"

version = "0.1.0"

readme = "README.md"

repository = "https://github.com/bobzhang/atd.mbt"

license = "BSD-3-Clause"

keywords = [ "atd", "json", "runtime" ]

description = "Runtime library of the MoonBit code generated by atdmbt (bobzhang/atd)"

source = "src"
