#!/usr/bin/env python3
"""
Generate MoonBit tests checking that the MoonBit atdcat produces the same
output as the reference OCaml atdcat.

Usage:
  scripts/gen_compat_tests.py <path to reference atdcat.exe>

The upstream ATD sources are expected in .repos/atd (see README.md).
The generated test files are written to src/atdcat/.
"""
import glob
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
UPSTREAM = os.path.join(ROOT, ".repos", "atd")
ERRORS = os.path.join(ROOT, "tests", "errors")
OUT_DIR = os.path.join(ROOT, "src", "atdcat")

# Inputs that trigger known, intentional deviations from upstream:
# - e060: upstream crashes with Invalid_argument("byte_of_dec")
# - e080: upstream crashes with Invalid_argument("Type_name.split ...")
# - e098: invalid UTF-8 in a string literal; MoonBit strings are Unicode
SKIP = {"e060.atd", "e080.atd", "e098.atd"}

FULL_OPTIONS = [
    [], ["-x"], ["-xk"], ["-xd"], ["-i"], ["-if"], ["-iv"],
    ["-remove-wraps"], ["-strip-all"], ["-strip", "json,doc"], ["-html-doc"],
    ["-ml", "foo"], ["-jsonschema", "root"],
    ["-jsonschema", "root", "-jsonschema-version", "draft-2019-09"],
    ["-jsonschema", "root", "-jsonschema-no-additional-properties"],
]
BASIC_OPTIONS = [[], ["-x", "-i"]]


def mbt_string(s):
    out = ['"']
    for c in s:
        o = ord(c)
        if c == '"':
            out.append('\\"')
        elif c == '\\':
            out.append('\\\\')
        elif c == '\n':
            out.append('\\n')
        elif c == '\r':
            out.append('\\r')
        elif c == '\t':
            out.append('\\t')
        elif o < 0x20 or o == 0x7f:
            out.append('\\u{%x}' % o)
        else:
            out.append(c)
    out.append('"')
    return ''.join(out)


def run(ref, cwd, args, stdin=None):
    p = subprocess.run([ref] + args, cwd=cwd, input=stdin,
                       capture_output=True)
    return (p.stdout.decode('utf-8'), p.stderr.decode('utf-8'),
            p.returncode)


def valid_utf8(data):
    try:
        data.decode('utf-8')
        return True
    except UnicodeDecodeError:
        return False


def gen(ref, name, cases, inputs):
    lines = [
        "// Generated by scripts/gen_compat_tests.py. DO NOT EDIT.",
        "// Expected outputs were produced by the reference OCaml atdcat.",
        "",
        "///|",
        "let %s_inputs : Map[String, String] = {" % name,
    ]
    for path, content in inputs:
        lines.append("  %s: %s," % (mbt_string(path), mbt_string(content)))
    lines.append("}")
    lines.append("")
    for i, (args, stdin_file, (out, err, code)) in enumerate(cases):
        title = "%s %d: atdcat %s" % (name, i, " ".join(args))
        if stdin_file:
            title += " < " + stdin_file
        lines += [
            "///|",
            "test %s {" % mbt_string(title),
            "  check_atdcat(",
            "    %s_inputs," % name,
            "    [%s]," % ", ".join(mbt_string(a) for a in args),
            "    stdin=%s," % (mbt_string(stdin_file) if stdin_file else "\"\""),
            "    stdout=%s," % mbt_string(out),
            "    stderr=%s," % mbt_string(err),
            "    code=%d," % code,
            "  )",
            "}",
            "",
        ]
    path = os.path.join(OUT_DIR, "compat_%s_test.mbt" % name)
    with open(path, "w") as f:
        f.write("\n".join(lines))
    print("wrote %s (%d cases)" % (path, len(cases)))


def main():
    ref = os.path.abspath(sys.argv[1])
    # Upstream test inputs, with all the options
    inputs, cases = [], []
    for path in sorted(glob.glob(os.path.join(UPSTREAM, "**", "*.atd"),
                                 recursive=True)):
        rel = os.path.relpath(path, UPSTREAM)
        data = open(path, "rb").read()
        if not valid_utf8(data):
            continue
        inputs.append((rel, data.decode('utf-8')))
        options = FULL_OPTIONS if rel.startswith("atdcat/") else BASIC_OPTIONS
        for opts in options:
            cases.append((opts + [rel], None, run(ref, UPSTREAM, opts + [rel])))
    # reading from stdin
    stdin_file = "atdcat/tests/input/test2.atd"
    data = open(os.path.join(UPSTREAM, stdin_file), "rb").read()
    cases.append(([], stdin_file, run(ref, UPSTREAM, [], stdin=data)))
    # multiple files (processed in reverse order, like upstream)
    multi = ["atdcat/tests/input/test2.atd", "atdcat/tests/input/schema.atd"]
    cases.append((multi, None, run(ref, UPSTREAM, multi)))
    gen(ref, "upstream", cases, inputs)

    # Malformed inputs
    inputs, cases = [], []
    for path in sorted(glob.glob(os.path.join(ERRORS, "*.atd"))):
        name = os.path.basename(path)
        if name in SKIP:
            continue
        data = open(path, "rb").read()
        inputs.append((name, data.decode('utf-8')))
        cases.append(([name], None, run(ref, ERRORS, [name])))
    gen(ref, "errors", cases, inputs)


if __name__ == "__main__":
    main()
